#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jackson-dataformats-binary
Version  : 2.8.1
Release  : 1
URL      : https://github.com/FasterXML/jackson-dataformats-binary/archive/jackson-dataformats-binary-2.8.1.tar.gz
Source0  : https://github.com/FasterXML/jackson-dataformats-binary/archive/jackson-dataformats-binary-2.8.1.tar.gz
Source1  : http://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.8.1/jackson-dataformat-smile-2.8.1.jar
Source2  : http://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.8.1/jackson-dataformat-smile-2.8.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-jackson-dataformats-binary-data = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
## Overview
This is a multi-module umbrella project for [Jackson](../../../jackson)
standard binary dataformat backends.

%package data
Summary: data components for the mvn-jackson-dataformats-binary package.
Group: Data

%description data
data components for the mvn-jackson-dataformats-binary package.


%prep
%setup -q -n jackson-dataformats-binary-jackson-dataformats-binary-2.8.1

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.8.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.8.1/jackson-dataformat-smile-2.8.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.8.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.8.1/jackson-dataformat-smile-2.8.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.8.1/jackson-dataformat-smile-2.8.1.jar
/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.8.1/jackson-dataformat-smile-2.8.1.pom
